const actionTypes = {
    CHANGE_SEARCH: 'CHANGE_SEARCH',
    CHANGE_COUNT: 'CHANGE_COUNT',
    CHANGE_TYPE: 'CHANGE_TYPE',
    LOAD_TWEETS: 'LOAD_TWEETS',
    TWEETS_LOADED: 'TWEETS_LOADED',
    LOAD_TWEETS_FAILURE: 'LOAD_TWEETS_FAILURE',
    SORT: 'SORT'
}

export default actionTypes;